### ISSUE TITLE
Support for NPM Private Modules

### ISSUE THREAD

**Issue by abhishekisnot** [mixu/npm_lazy#52]
Please add support for recently introduced [NPM Private Modules](https://www.npmjs.com/private-modules).

**Comment by CL0SeY** [comment]
Hi @abhishekisnot can you please give my fix a try.

If all good we'll look at putting this into the next version.

**Comment by JakeChampion** [comment]
Works for me :+1:

**Comment by abhishekisnot** [comment]
Yup works for me too

**Comment by CL0SeY** [comment]
Note that a side effect of this will mean any private or even public but _scoped_ modules will _not_ be cached, so as these type of modules become more prevalent there may be a performance hit.

Also I wonder... is using the pure straight-through connection for these private modules causing further modules down the chain to be loaded from https://registry.npmjs.com instead of the proxy? This would not be the best for performance either. I can check some time in the new year perhaps.

**Comment by killthrush** [comment]
This worked for me, although I needed to hack line 27 to `if (name.indexOf('@', 0) === 0) {`.  I'm pretty sure this is an ES5 thing... thoughts?

**Comment by CL0SeY** [comment]
I've refactored it a bit - can you see all these changes:
https://github.com/mixu/npm_lazy/pull/56/files

**Comment by killthrush** [comment]
Looks like [your latest commit](https://github.com/CL0SeY/npm_lazy/commit/df10cf9d534487bad80038f1f619418779602b85) fixes my problem.  I was able to run through the whole install without a problem.  Thanks!
